### PR TITLE
pseudo Devtools and newtab added in edge

### PR DESCRIPTION
**Pull request by MalayGain**
#32 improve browser

### CODE REVIEW

**Comment by andrewstech** [comment]
Hi @MalayGain Thankyou for your contribution to the project. I was wondering how you launch Devtools as I can't seem to find a button.

**Comment by blueedgetechno** [comment]
@andrewstech I will take care of this pull request. I will test it locally and will make the required changes.

**Comment by andrewstech** [comment]
> @andrewstech I will take care of this pull request. I will test it locally and will make the required changes.

Ok

**Comment by MalayGain** [comment]
yes locally it was there, I will check and try to fix the issues .

**Pull request merged**
