### PR TITLE
Move "Known Issues" Section

### PR DESCRIPTION
**Pull request by Lukas-Batema**
*Dear windows11 Maintainers,*

---
I moved this section up, so it will be more noticeable, and hopefully will result in less repeat issues made on the repo. I also changes the header type, to fit where it was put.

###### EDIT: I have to fix something on it, so it will be in 2 commits...

---
> _Best Wishes,
>Lukas Batema_

### CODE REVIEW

**Comment by Lukas-Batema** [comment]
Why does this bot spam that message, tho???

**Comment by blueedgetechno** [comment]
It would be an exaageration to say that firefox blur issue is the cause for repeated issues. Infact there is only one.

**Comment by Lukas-Batema** [comment]
> It would be an exaageration to say that firefox blur issue is the cause for repeated issues. Infact there is only one.

I realise that, but if you, in the long run, put more known issues, listed there, it would be more noticeable. This would be helpful in the long run, not just short-term.

**Comment by blueedgetechno** [comment]
Readme was for introducng the project. I added the firefox blur issue just for people starting out and it will be removed eventually.

**Comment by Lukas-Batema** [comment]
> Readme was for introducng the project. I added the firefox blur issue just for people starting out and it will be removed eventually.

Ah, ok. I do think having a section of known “major” issues in the readme file, near the top, would be a good idea. It’s up to you though :)

**Comment by blueedgetechno** [comment]
I would rather include them in default issue template than readme. lol

**Comment by Lukas-Batema** [comment]
> I would rather include them in default issue template than readme. lol

Understood :) I will close this then ;)

**Pull request closed without merging**
