### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Tronic247**
Updates, please merge or this PR will die

### CODE REVIEW

**Comment by blueedgetechno** [comment]
state your changes

**Comment by Tronic247** [comment]
Changed the calendar (font + make items square)
Changed `filter:drop-shadow` to `box-shadow`
Changed font sizes
Changed start menu all apps animation

**Comment by Tronic247** [comment]
Why the `other` label?

**Comment by blueedgetechno** [comment]
You changed a lot of original changes I had done to your previous pull request like calender, about window and what not. It has to look visibly same to work. Also for few things filter-shadow is must like non-square icons.

**Pull request closed without merging**
