### PR TITLE
HUGE Improvements

### PR DESCRIPTION
**Pull request by Tronic247**
## Things updated

1. Smooth animations
2. loading screen
3. Calendar UX
4.  Much more !

### CODE REVIEW

**Comment by blueedgetechno** [comment]
Oh my dear, its so awesome for you.

Unfortunately I have to hold this pr untill the spotify push otherwise it will create too much of merge conflicts for me to handle.
I hope you understand.

**Comment by Tronic247** [comment]
No problem @blueedgetechno. And thanks for the star !

**Comment by andrewstech** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/blueedgetechno/reviewers)

**Review by andrewstech — APPROVED** [review]
Wow You have been busy.

**Comment by blueedgetechno** [comment]
fix the body overflow

**Comment by Tronic247** [comment]
> 
> 
> fix the body overflow



@blueedgetechno => https://discord.com/channels/868499076432408627/868499076432408631/878503034857087026

**Pull request closed without merging**
