### PR TITLE
Added Power controls #46, Boot & login screen #78, Few design and bug fixes

### PR DESCRIPTION
**Pull request by blueedgetechno**
The comprehensive Boot & Login screen has been made, along with power controls like Shut down, Restart and Lock in the start menu.

The boot screen and login screen follow a straight line mechanism (Boot state -> locked state -> unlocked state). The boot screen is loaded the earliest and keeps loading until a redux action is triggered when the entire site is loaded.

To avoid any feature failure, the boot and login screen component has been made in a separate component file which uses minimum states to avoid unnecessary conflicts.

Many redux actions have been added to suit the demand of the feature. [see preview here](dev.blueedge.me)

### Loading screen
Screenshot (89)

### Lock screen
image

### CODE REVIEW

**Comment by Lukas-Batema** [comment]
Agk, I cannot unlock the "device", when clicking the return key,?with or without text in the password field...

**Comment by blueedgetechno** [comment]
@Lukas-Batema There is a button for that

**Comment by Lukas-Batema** [comment]
> @Lukas-Batema There is a button for that

On most WinOS's, you can also click the return key, to login, instead of the onscreen button.

**Comment by Lukas-Batema** [comment]
I can still scroll of the edge of the screen, but if you do centre it just right, it looks great!
image

**Comment by blueedgetechno** [comment]
Return key will be added in next push, about the overflow in mobile I tried the limiting zooming but it doesn't seem to work.

**Comment by Lukas-Batema** [comment]
> Return key will be added in next push, about the overflow in mobile I tried the limiting zooming but it doesn't seem to work.

I will try something in my fork later today. I think I know what's wrong.

**Pull request merged**
